### ISSUE TITLE
Idea: Include the remote pay style

### ISSUE THREAD

**Issue by aezell** [fuzz/remote#20]
Some remote organizations modify their employee's pay based on their geographic location or they pay everyone equivalent to their main office location (if it exists).

This information, if available, could be helpful. 

Additionally, we could include if the companies hire remote globally or only in a particular region/country.

**Comment by fuzz** [comment]
Thanks!

As for the latter, that info is communicated by the office location, whether or not there or more offices and the `Do` code to indicate domestic only. It’s fairly common for companies to only allow remote work in countries where they have offices. I don’t want to get into listing every office/country, so if you see `Do` with San Francisco and no other offices that’s US only. If you see the same but there are other offices then you have to look into where the other offices are located.

As for the former, I don’t want to make it required as the info may not be available, but I think it’s a great addition. I will add it, probably next week.


:Fuzz

**Comment by aezell** [comment]
Hi @fuzz. That makes a lot of sense. Thank you for explaining the details and considering this extra info.
